language: python

python:
    - 2.7
    - 3.3
    - 3.4
    - pypy
    - nightly
compiler:
    - gcc
    - clang
script:
    - python setup.py build
    - python setup.py install
    - python unitTests.py